### ISSUE TITLE
Problem with the Command Line Interface

### ISSUE THREAD

**Issue by marcell10651** [MoseleyBioinformaticsLab/pdb_eda#4]
I read your other closed issue which stated that there was a problem with the Command Line Interface and it was already resolved, because if I have seen corretly, you have already released version 1.1 of the package in which the problem would be solved.
Howerever I tried using the Command Line Interface and the issue still persists. I checked and the version I have got is 1.1.0. By this I assume that I already am using the latest version available in which the bug was fixed. I even reinstalled the package, to no avail.
I seem to be getting the same error message which you have mentioned in your earlier post ("Cryptic error message from a simple failure #1"). To be safe I will copy paste the error message I am getting below:

```
Traceback (most recent call last):
  File "C:\Users\username\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\username\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\username\AppData\Local\Programs\Python\Python37\lib\site-packages\pdb_eda\__main__.py", line 51, in <module>
    main(args)
  File "C:\Users\username\AppData\Local\Programs\Python\Python37\lib\site-packages\pdb_eda\__main__.py", line 44, in main
    singleStructure.main(args)
  File "C:\Users\username\AppData\Local\Programs\Python\Python37\lib\site-packages\pdb_eda\singleStructure.py", line 28, in main
    analyser.aggregateCloud(radii, slopes, atomL=True, residueL=True, chainL=True)
AttributeError: 'int' object has no attribute 'aggregateCloud'
```
The command I am trying to run is the following:

`python -m pdb_eda 3UBK 3ubk.txt --atom --out-format=csv`

I tried looking into solving it myself, but I am nowhere near to being qualified, as I have extremely shallow knowledge of Python. Becasuse of this fact, it is possible that I overlooked something and there could be a simple solution to my problem which I have failed to notice. Also, this is my first time posting on GitHub, so please bear with me if I have done something in an inappropriate way.
Thank you in advance,
-marcell10651

**Comment by hunter-moseley** [comment]
Marcell

I have a massive upgrade for pdb_eda that is coming.
In it, I fixed this minor issues along with improving computational performance roughly 3-fold and greatly expanding the API and CLI.  It will likely take another 2 weeks for this next major version of pdb_eda to be pushed to GitHub and PyPI.

**Comment by marcell10651** [comment]
Thank you very much for your fast answer!
