### ISSUE TITLE
Working with Cryo-EM

### ISSUE THREAD

**Issue by marcell10651** [MoseleyBioinformaticsLab/pdb_eda#5]
I am currently working with pdb_eda using XRD maps which are useful, but I think that Cryo-EM structures would offer me greater benefit.
I tried to perform calculations with a structure recorded in Cryo-EM, but it doesn't seem to be working. Is it possible to work with these kind of structures or does pdb_eda only support XRD maps?

**Comment by hunter-moseley** [comment]
The pdb_eda package was only designed to work with x-ray diffraction maps.  We might expand it in the future, but I have no time-table of when that could be.

**Comment by marcell10651** [comment]
Thank you very much again for Your rapid reply!
